package tamizdat

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"fmt"
	"math/big"
	"time"
)

// padCertChain appends N dummy CA-style certificates to the leaf cert's
// chain so that the encrypted Certificate message in the TLS 1.3 handshake
// approximates the byte-count of a real CDN cert chain (e.g. ok.ru -> ~3 certs,
// ~4 KB DER total). Without padding, our self-signed single cert (~1 KB) emits
// a noticeably smaller encrypted-flight than the masquerade target, giving an
// Aparecium-class detector a passive size-based signal even though TLS 1.3
// encrypts the certificate contents.
//
// The padding certs are valid X.509 (so TLS framing accepts them) but do NOT
// chain up to the leaf -- they're filler bytes that look like CA certificates
// to a passive observer. Clients with InsecureSkipVerify (our case) ignore
// them. Standard verifying clients would reject the connection at the
// Certificate verification step regardless, since our leaf is self-signed.
//
// targetExtraBytes is the desired padding size; we generate certs until the
// total padding meets/exceeds the target, then stop. Typical: 3000-4000 bytes
// to match GlobalSign-class chains.
func padCertChain(leafChain [][]byte, targetExtraBytes int, dummyCount int) ([][]byte, error) {
	if dummyCount <= 0 {
		dummyCount = 2
	}
	if targetExtraBytes <= 0 {
		targetExtraBytes = 3500
	}

	out := make([][]byte, 0, len(leafChain)+dummyCount)
	out = append(out, leafChain...)

	added := 0
	for i := 0; i < dummyCount; i++ {
		certDER, err := generateDummyCACert()
		if err != nil {
			return nil, fmt.Errorf("generating padding cert #%d: %w", i, err)
		}
		out = append(out, certDER)
		added += len(certDER)
		if added >= targetExtraBytes {
			break
		}
	}
	return out, nil
}

// generateDummyCACert produces a self-signed RSA-2048 CA-looking certificate
// suitable for use as TLS chain padding. ~1.5 KB DER. The Subject and Issuer
// are randomized strings so two padding chains generated by the same server
// are not byte-identical (avoids a separate "twin-padding-cert" detector).
func generateDummyCACert() ([]byte, error) {
	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, err
	}

	// Random suffix to avoid identical Subject across instances.
	rb := make([]byte, 8)
	if _, err := rand.Read(rb); err != nil {
		return nil, err
	}
	suffix := fmt.Sprintf("%x", rb)

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, err
	}

	// Pick CA-flavoured subject so the cert "looks like" a legitimate CA when
	// rendered. Field shapes mirror GlobalSign / DigiCert / Sectigo intermediates.
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			Country:            []string{"US"},
			Organization:       []string{"Internet Trust Services CA-" + suffix},
			OrganizationalUnit: []string{"Edge TLS"},
			CommonName:         "Edge TLS Intermediate CA " + suffix,
		},
		Issuer: pkix.Name{
			Country:      []string{"US"},
			Organization: []string{"Internet Trust Services Root"},
			CommonName:   "Internet Trust Services Root R3",
		},
		NotBefore:             time.Now().Add(-365 * 24 * time.Hour),
		NotAfter:              time.Now().Add(10 * 365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLenZero:        false,
		MaxPathLen:            1,
	}

	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &priv.PublicKey, priv)
	if err != nil {
		return nil, err
	}
	return der, nil
}
